#Expyriment 1.0.0 (Python 3.11.2), .xpe-file, coding: UTF-8
#date: Sun Oct 05 2025 11:57:42
#sha1: f88dbe
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='anna', release='6.1.0-37-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22)', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
143,stderr,received,'Traceback (most recent call last):'
143,stderr,received,'  File "/home/anna/ENS/3A/cogsup/exp_app/PPE/Week-4/Exercises/drawing_functions.py", line 41, in <module>'
143,stderr,received,'    present_for(stims, 500)'
144,stderr,received,'  File "/home/anna/ENS/3A/cogsup/exp_app/PPE/Week-4/Exercises/drawing_functions.py", line 17, in present_for'
144,stderr,received,'    timed_draw(stims, exp)'
144,stderr,received,'  File "/home/anna/ENS/3A/cogsup/exp_app/PPE/Week-4/Exercises/drawing_functions.py", line 9, in timed_draw'
144,stderr,received,'    t0 = exp.clock.time'
144,stderr,received,'         ^^^^^^^^^'
144,stderr,received,"AttributeError: 'int' object has no attribute 'clock'"
